---
title: "Covid"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(roll)
library(magrittr)

# import data frames COVID: cases, tests and population size of municipalities
dc <- read_delim(here("exercises", "ws02", "covid", "Municipality_cases_time_series.csv"), ";", escape_double = FALSE, trim_ws = TRUE)
dt <- read_delim(here("exercises", "ws02", "covid", "Municipality_tested_persons_time_series.csv"), ";", escape_double = FALSE, trim_ws = TRUE)
dsize <- read_delim(here("exercises", "ws02", "covid", "Municipality_test_pos.csv"), ";", escape_double = FALSE, trim_ws = TRUE)

# make data tidy
dc %<>%
  pivot_longer(cols = !date_sample, names_to = "kommune", values_to = "casesDiagnosed") %>% arrange(kommune, date_sample)

dt %<>%
  pivot_longer(cols = !PrDate_adjusted, names_to = "kommune", values_to = "testsConducted") %>%
  arrange(kommune, PrDate_adjusted) %>%
  rename(date_sample = PrDate_adjusted)

# check there are no NA in the set
sum(is.na(dc$casesDiagnosed))
sum(is.na(dt$testsConducted))
sum(is.na(dt$testsConducted))
sum(is.na(dsize$Befolkningstal))

# make data compatible rename columns for merging and
dsize <- dsize %>%
  select(contains("Kom"), Befolkningstal) %>%
  rename("kID" = `Kommune_(id)`, "kommune" = `Kommune_(navn)`, population = Befolkningstal) %>%
  mutate(population = population * 1000) %>%
  select(-kID)

# check Kommune name can be used as key
dc[!(dc$kommune %in% dsize$kommune), ]$kommune
dsize[!(dsize$kommune %in% dt$kommune), ]$kommune
dt[!(dt$kommune %in% dsize$kommune), ]$kommune

# ooops!
# for some reason one data frame uses Københaven the other Copenhagen),
dc$kommune <- str_replace(dc$kommune, "Copenhagen", "København")
dt$kommune <- str_replace(dt$kommune, "Copenhagen", "København")
# check again keys are clean OK re-run rows 35-37

# merge data together
dc <- merge(dc, dsize)
dt <- merge(dt, dsize)

# create new variables (e.g. rolling aggregates)
dc %<>%
  group_by(kommune) %>%
  mutate(
    casesDPer100k = casesDiagnosed / (population / 1000),
    dcr7d = roll_sum(casesDiagnosed, width = 7, min_obs = 1),
    dcr7dPer100k = dcr7d / (population / 1000),
    dcr7dPer100kCh1 = lag(dcr7dPer100k, 1) - dcr7dPer100k,
    dcr7dPer100kCh3 = lag(dcr7dPer100k, 3) - dcr7dPer100k,
    dcr7dPer100kCh7 = lag(dcr7dPer100k, 7) - dcr7dPer100k
  )

dt %<>%
  group_by(kommune) %>%
  mutate(
    testsPer100k = testsConducted / (population / 1000),
    tr7d = roll_sum(testsConducted, width = 7, min_obs = 1),
    tr7dP100k = tr7d / (population / 1000),
    tr7dP100kCh1 = lag(tr7dP100k, 1) - tr7dP100k,
    tr7dP100kCh3 = lag(tr7dP100k, 3) - tr7dP100k,
    tr7dP100kCh7 = lag(tr7dP100k, 7) - tr7dP100k
  )

# merge test with case data
df <- merge(dc, dt)

df$PosTestRate7d <- df$dcr7dPer100k / df$tr7dP100k

# check there were no diagnosis without tests
sum(df$casesDiagnosed > df$testsConducted)
```

## Covid data analysis DK overview


```{r cars}

```

## Including Plots



```{r}
devtools::install_github("sebastianbarfort/mapDK")
devtools::install_github("56north/leafletDK")

library(mapDK)
library(mapview)
library(leaflet)
library(leafletDK)
library(tmap)
library(stringr)
library(maps)
library(ggmap)
library(rgdal)
library(dplyr)
library(tmap)
library(spData)
library(sf)
library(sp)
library(geojsonR)
library(BBmisc)
# tmap_mode("view")

register_google(key = "AIzaSyBEPq4eqOeI6-O5CjjAUcugcAj3oHSD9lE")

#########################
######## LEAFLET ########
#########################
dk <- st_read("gadm36_DNK_2.shp")

dk %>%
  ggplot() +
  geom_sf() +
  theme_bw()
# cleaning some names that differed in the datasets
dk$NAME_2 <- str_replace(dk$NAME_2, "Århus", "Aarhus")
dk$NAME_2 <- str_replace(dk$NAME_2, "Høje Taastrup", "Høje-Taastrup")
dk$NAME_2 <- str_replace(dk$NAME_2, "Vesthimmerland", "Vesthimmerlands")

# joining the population to the shapefile
dk_pop <-
  dsize %>%
  left_join(dk, by = c("kommune" = "NAME_2"))

## DK coordinates, so i dont have to google them
## lng 9.501785
## lat 56.26392

# transforming the df into a shapefile again, that makes us use the geometry points
df_dk <- st_as_sf(dk_pop, sf_column_name = "geometry")

#getting the centroids to grab the coordinates from the dataset
dk_cent <- st_centroid(df_dk)
dk_coords <- st_coordinates(dk_cent)

#converting the matrix into a df again
dk_coords_next <- as.data.frame(dk_coords)

#adding the coordinates to the kommunes and their population
dk_merge_coords <-
  dsize %>%
  cbind(dk_coords_next)

#merging the coords/kommunes with the covid data
dk_merge_coords_test <-
  df %>%
  merge(dk_merge_coords)

#merging the covid data into the shapefile to plot it
df_dk_covid <-
  df %>%
  filter(date_sample == "2020-03-14") %>%
  merge(df_dk)

#to plot the data it needs to be a shapefile (sf) again - creating shapefile
#and specifying where it should take sf data from
df_dk_covid <- st_as_sf(df_dk_covid, sf_column_name = "geometry")

#filtering for a single date to not cause overplotting
df_one_date <- dk_merge_coords_test %>%
  filter(date_sample == "2020-03-14")

# test<-
# one_date%>%
# #filter out copenhagen here
# group_by(kommune)%>%
# summarize(
# X_max = max(~X),
# X_min = min(~X),
# )

########### MAP###########

#getting the absolute values - converting the negative values into 0
#to later normalize
a_one_date<-
  df_one_date%>%
  mutate(
    a_dcr7dPer100kCh1 = abs(dcr7dPer100kCh1),
    a_dcr7dPer100kCh3 = abs(dcr7dPer100kCh3),
    a_dcr7dPer100kCh7 = abs(dcr7dPer100kCh7)
  ) %>% ungroup()

#normalizing the change variables
 normality<-function(m){
   (m - min(m))/(max(m)-min(m))
 }

 
a_one_date %>%
  mutate(
    n_dcr7dPer100kCh1 = normality(a_dcr7dPer100kCh1),
    n_dcr7dPer100kCh3 = normality(a_dcr7dPer100kCh3),
    n_dcr7dPer100kCh7 = normality(a_dcr7dPer100kCh7)
  ) 



# change_icons <- iconList(
#   ch1_icon = makeIcon(ifelse(one_date$dcr7dPer100kCh1 <= 0, "rect_green.png", "rect_red.png"), iconWidth = a_one_date$n_dcr7dPer100kCh1, iconHeight = "10"),
#   ch3_icon = makeIcon(ifelse(one_date$dcr7dPer100kCh3 <= 0, "rect_green.png", "rect_red.png"), iconWidth = a_one_date$n_dcr7dPer100kCh3, iconHeight = "10"),
#   ch7_icon = makeIcon(ifelse(one_date$dcr7dPer100kCh7 <= 0, "rect_green.png", "rect_red.png"), iconWidth = a_one_date$n_dcr7dPer100kCh7, iconHeight = "10")
# )

a_one_date %<>%
  mutate(
    y_dcr7dPer100kCh1 = ((plogis(dcr7dPer100kCh1*10)-0.5)*188),
    y_dcr7dPer100kCh3 = ((plogis(dcr7dPer100kCh3*10)-0.5)*188),
    y_dcr7dPer100kCh7 = ((plogis(dcr7dPer100kCh7*10)-0.5)*188),
    custlng_dcr7dPer100kCh1 = cos(y_dcr7dPer100kCh1),
    custlng_dcr7dPer100kCh3 = cos(y_dcr7dPer100kCh3),
    custlng_dcr7dPer100kCh7 = cos(y_dcr7dPer100kCh7),
    custlat_dcr7dPer100kCh1 = sin(y_dcr7dPer100kCh1),
    custlat_dcr7dPer100kCh3 = sin(y_dcr7dPer100kCh3),
    custlat_dcr7dPer100kCh7 = sin(y_dcr7dPer100kCh7)
  ) 

df_map<-
  a_one_date%>%
  select(kommune, population, X, Y,
         custlng_dcr7dPer100kCh1,
         custlng_dcr7dPer100kCh3,
         custlng_dcr7dPer100kCh7,
         custlat_dcr7dPer100kCh1,
         custlat_dcr7dPer100kCh3,
         custlat_dcr7dPer100kCh7) %>%
  mutate(
    custlng_Ch1 = X + normality(abs(custlng_dcr7dPer100kCh1)),
    custlng_Ch3 = X + normality(abs(custlng_dcr7dPer100kCh3)),
    custlng_Ch7 = X + normality(abs(custlng_dcr7dPer100kCh7)),
    custlat_Ch1 = Y + normality(abs(custlat_dcr7dPer100kCh1)),
    custlat_Ch3 = Y + normality(abs(custlat_dcr7dPer100kCh3)),
    custlat_Ch7 = Y + normality(abs(custlat_dcr7dPer100kCh7)),
  )



myMap<-leaflet() %>%
  addTiles() %>%
  setView(lng = 9.501785, lat = 56.26392, zoom = 7) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    data = df_dk_covid, color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~ colorQuantile("YlOrRd", dcr7d)(dcr7d), # changing the municipality color based on a specific variable
    label = df_dk_covid$kommune
  )

  for (i in 1:nrow(df_map))
  myMap<-myMap%>%
  addPolylines(
    lng=c(df_map[i,]$X, df_map[i,]$custlng_Ch1), lat=c(df_map[i,]$Y, df_map[i,]$custlat_Ch1),
    #color=ifelse(a_one_date$dcr7dPer100kCh1 < 0, "green", "red"),
    #opacity = ifelse(a_one_date$dcr7dPer100kCh1 == 0, 0, 0.5)
  ) %>%
  addPolylines(
    lng=c(df_map[i,]$X, df_map[i,]$custlng_Ch3), lat=c(df_map[i,]$Y+0.02, df_map[i,]$custlat_Ch3),
    #color= ifelse(a_one_date$dcr7dPer100kCh3 < 0, "green", "red"),
    #opacity = ifelse(a_one_date$dcr7dPer100kCh3 == 0, 0, 0.5)
  ) %>%
  addPolylines(
    lng=c(df_map[i,]$X, df_map[i,]$custlng_Ch7), lat=c(df_map[i,]$Y+0.04, df_map[i,]$custlat_Ch7),
    #color=ifelse(a_one_date$dcr7dPer100kCh7 < 0, "green", "red"),
    #opacity = ifelse(a_one_date$dcr7dPer100kCh7 == 0, 0, 0.5)
  )
  myMap
  
  
  
  # addRectangles(
  #   data=df_map, ~X, ~Y, ~custlng_Ch1, ~Y,
  #   group=a_one_date$kommune,
  #   color=ifelse(a_one_date$dcr7dPer100kCh1 < 0, "green", "red"),
  #   opacity = ifelse(a_one_date$dcr7dPer100kCh1 == 0, 0, 0.5)
  # ) %>%
  # addRectangles(
  #   data=df_map, ~X, ~Y+0.02, ~custlng_Ch3, ~Y+0.02,
  #   group=a_one_date$kommune,
  #   color= ifelse(a_one_date$dcr7dPer100kCh3 < 0, "green", "red"),
  #   opacity = ifelse(a_one_date$dcr7dPer100kCh3 == 0, 0, 0.5)
  # ) %>%
  # addRectangles(
  #   data=df_map, ~X, ~Y+0.04, ~custlng_Ch7, ~Y+0.04,
  #   group=a_one_date$kommune,
  #   color=ifelse(a_one_date$dcr7dPer100kCh7 < 0, "green", "red"),
  #   opacity = ifelse(a_one_date$dcr7dPer100kCh7 == 0, 0, 0.5)
  # )



  # addMarkers(
  #   data = one_date, ~X, ~Y,
  #   icon = ~ change_icons$ch7_icon,
  #   label = one_date$dcr7dPer100kCh7
  # ) %>%
  # addMarkers(
  #   data = one_date, ~X, ~ Y + 0.02, # off-setting the second marker by 0.02 latitude
  #   icon = ~ change_icons$ch3_icon,
  #   label = one_date$dcr7dPer100kCh3
  # ) %>%
  # addMarkers(
  #   data = one_date, ~X, ~ Y + 0.04,
  #   icon = ~ change_icons$ch1_icon,
  #   label = one_date$dcr7dPer100kCh1
  # ) %>% 



```
